### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by cyr3ne** [GingerBeardx/prj-rev-bwfs-dasmoto#1]
https://github.com/GingerBeardx/prj-rev-bwfs-dasmoto/blob/368b2f05c1ad56af96d2052352929aede80af156/Dasmotos/index.html#L23

Awesome, I like that you saved the photos in the project. Some people take the easy way out and link externally haha

**Comment by GingerBeardx** [comment]
I did have a hard time with the background image and couldn't figure out what was wrong.  I actually have been going through the Git stuff today and the video, "Using Git and GitHub," actually let me know what I was doing wrong.  I needed an extra period at the beginning of my path and it would have worked fine.  I've updated my local version so I can reference back to it if I need to :)
